Add setting to choose invoice prefix (defaults to Civi-)
agileware/au.com.agileware.civiquickbooks pull request #25
Opened 2021-05-18 00:49 UTC by ananelson

2021-05-18 02:14 UTC, ananelson commented
This also standardizes the remainder of the invoice number to ensure proper sorting by prepending zeros.

2021-06-21 00:39 UTC, agileware-fj requested changes
The concept behind this is sound, and I'd merge immediately if it wasn't for enforcing the 7 digits of invoice number.

I don't think any of our own clients have breached the 100,000 invoice mark, which makes this extra two (often three) digits awkward in their invoices. It seems like QBO should be capable of sorting numerically on the invoice field anyway, although I haven't tested this yet. In this case is this for offline sorting tools?
Edit: And of course, on testing, it seems like QBO in fact does **not** sort numerically on the invoice number field, but by character.

I think it would be better then to be able to specify a format with a reasonable default, possibly even just `'Civi-%u'` so that the invoice number remains better readable to humans.

Note that this will also require validation to be added to the settings form to make sure the invoice prefix format us usable, e.g.
`strpos(sprintf($invoice_id_format, 99999), '99999') !== FALSE)`.

@ananelson do you have any thoughts on this, and can you update your PR accordingly? (Otherwise will adjust as required and merge when I have time)

2021-06-21 00:39 UTC, agileware-fj commented on CRM/Civiquickbooks/Invoice.php
> +        $new_invoice['DocNumber'] = $invoice_prefix . sprintf("%07d", $db_contribution['id']);
Alternative would be to do `sprintf($invoice_prefix, $db_contribution['id'])` where `$invoice_prefix` is in the format `'Civi-%07d'` (for this example)

2021-06-21 00:39 UTC, agileware-fj commented on settings/civiquickbooks.setting.php
> +    'default' => 'Civi-',
`'Civi-%07d'` to use format

2022-10-17 03:13 UTC, agileware-fj commented
Rebased, applied suggested edit (default will remain the same), and merged.

Thanks @ananelson for starting this enhancement

2022-10-17 03:13 UTC, closed without merging